### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MaxLyons** [Gacnt/go-pubg#1]
Any idea if this method still works?

**Comment by Ettudis** [comment]
"Everything works, just need to build the structs for Unmarshalling the JSON data into upon successful query". Might want to start there.

**Comment by MaxLyons** [comment]
Oh wow. How are you acquiring the ticket?

**Comment by Gacnt** [comment]
Hey sorry I didn't see this until now. It connects to the web socket server etc but I haven't gotten around to building the structs to unmarshal the JSON into, to get the ticket you need to manually do it using WireShark for now. I looked into generating the ticket through the app, but I tracked it back into the game engine its self which would require reverse engineering the executable (or it could possibly be on the server end its self)

**Comment by MaxLyons** [comment]
Yeah seems cool, but it seems like the WS packets are not showing up in wireshark anymore? It's encrypted. Do you have discord or steam?

**Comment by Lindefelt** [comment]
If you force the Client to connect over HTTP instead of HTTPS you can read the ticket with wireshark. 

You can also  use fiddler+proxifier forcing the client with proxifier to connect via your fiddler proxy. Then You can read the HTTP&HTTPS traffic in fiddler.

**Comment by MaxLyons** [comment]
Okay, thanks for the info! Would it be possible to get in contact with you? What is the best way? I'd be willing to pay if you could help me out!

Cheers.

**Comment by Lindefelt** [comment]
you can get in touch with me on discord Lindefelt#7313

**Comment by MaxLyons** [comment]
Awesome. Added you. I'm maxlyons#5533
